---
title: "R Notebook"
output:
  html_document:
    pairs.df_print: paged
---


```{r}
library(tidyr)
library(dplyr)
library(data.table)
library(ggplot2)

# files needed
z_scores_file <- '/scratch/groups/abattle4/victor/GTExV6PRareVariationData/archive/data/v8/outliers_medz_zscores.txt'
rare_var_pairs_file <- '/scratch/groups/abattle4/victor/GTExV6PRareVariationData/archive/reference/gene_indiv_variants.txt'
afr_indiv_file <- '/scratch/groups/abattle4/victor/GTExV8_RareVariationData/reference/gtex_v8_wgs_individuals_AFA.txt'

# read in files needed
z_scores <- read.table(z_scores_file, header=TRUE, check.names = FALSE) # wide table with z scores for gene-individual pairs
rare_var_pairs <- read.table(rare_var_pairs_file, header=TRUE, check.names = FALSE) # table of gene-individual pairs with their rare variants
afr_indiv <- as.character(read.table(afr_indiv_file)$V1) # list of African American individuals with WGS

# convert to long table with three columns: gene, individual, zscore
gene_list <- colnames(z_scores)[-1]
pairs.df <- gather_(z_scores, key="indiv", value="zscore", gene_list)

# remove gene-individuals with NA zscores
pairs.df <- drop_na(pairs.df, zscore)

# filter for African individuals only
pairs.df <- filter(pairs.df, (indiv %in% afr_indiv))

# add column to pairs.df which indicates if the given gene-individual pair has at least 1 rare variant within 10kb of gene TSS
rare_var_pairs$easykey <- paste0(rare_var_pairs$gene,rare_var_pairs$individual)
pairs.df$easykey <- paste0(pairs.df$GENE,pairs.df$indiv)
pairs.df$has_rare <- ifelse(pairs.df$easykey %in% rare_var_pairs$easykey,1,0)

# compute enrichment at various Zscore thresholds
zscore_thresh_list <- seq(1,5, 0.5)

# determine inlier/outlier status based on Zscore thresholds
for (thresh in zscore_thresh_list) {
  pairs.df[[paste0("outlier_status_at_thresh_",thresh)]] <- ifelse(abs(pairs.df$zscore) > thresh, "outlier","inlier")
}

pairs.df <- pairs.df %>% 
    gather(contains("thresh"), key=thresh,value=outlier)

# sort by gene name and zscore
pairs.df <- pairs.df[order(pairs.df$GENE,pairs.df$zscore),]

# limit to genes with at least 1 outlier at the given threshold
count.table.list <- list()
rare.count.table.list <- list()

for (i in seq_along(zscore_thresh_list)){
  t <- zscore_thresh_list[i]
  tmp <- filter(pairs.df, outlier == "outlier", thresh == paste0("outlier_status_at_thresh_",t))
  genes_keep <- unique(tmp$GENE) # genes with at least 1 outlier individual

  pairs.at.thresh.df <- filter(pairs.df, GENE %in% genes_keep, thresh == paste0("outlier_status_at_thresh_",t))

  # frequency table to count inliers and outliers with or without rare variants
  count.table.list[[i]] <- pairs.at.thresh.df %>%
    group_by(thresh) %>%
    count(outlier) %>%
    pivot_wider(names_from=outlier,values_from=n) %>%
    rename(outlier_all_pairs=outlier, inlier_all_pairs=inlier)

  # frequency table to count inliers and outliers (with  rare variants)
  rare.count.table.list[[i]] <- pairs.at.thresh.df %>%
    filter(has_rare == 1) %>%
    group_by(thresh) %>%
    count(outlier) %>%
    pivot_wider(names_from=outlier,values_from=n) %>%
    rename(outlier_rare_pairs=outlier, inlier_rare_pairs=inlier)
}

# combine count tables together
count.table <- rbindlist(count.table.list)
rare.count.table <- rbindlist(rare.count.table.list)

# compute enrichment
enrichment.df  <- merge(count.table,rare.count.table,by="thresh",all=T) %>% mutate(numerator=outlier_rare_pairs/outlier_all_pairs, denominator=inlier_rare_pairs/inlier_all_pairs, enrichment=numerator/denominator)

# confidence intervals
enrichment.df <- enrichment.df %>% mutate(log_se = sqrt(1/outlier_rare_pairs - 1/outlier_all_pairs + 1/inlier_rare_pairs - 1/inlier_all_pairs), lower_CI = enrichment * exp(-1.96*log_se), upper_CI = enrichment * exp(1.96*log_se))


# sorting rows by z score threshold
enrichment.df$sortcol <- as.numeric(gsub("outlier_status_at_thresh_", "", enrichment.df$thresh))
enrichment.df <- arrange(enrichment.df, sortcol)

enrichment.plot <- ggplot(enrichment.df, aes(x = sortcol, y = enrichment)) +
  geom_point(size = 2) + 
  geom_text(aes(label = outlier_all_pairs), hjust = 0.7, vjust = -4) + 
  geom_errorbar(aes(ymax = upper_CI, ymin = lower_CI))
print(enrichment.plot + labs(title="Enrichment of rare variants in outlier genes \n(genes have at least 1 outlier individual)", x = "Z-score threshold"))


```

```{r}
# don't limit to genes with at least 1 outlier at the given threshold

# build frequency table to count inliers and outliers with or without rare variants
count_table <-
    pairs.df %>%
    group_by(thresh) %>%
    count(outlier) %>%
    pivot_wider(names_from=outlier,values_from=n) %>%
    rename(outlier_all_pairs=outlier, inlier_all_pairs=inlier)

# build frequency table to count inliers and outliers (with  rare variants)
rare_count_table <-
    pairs.df %>%
    filter(has_rare == 1) %>%
    group_by(thresh) %>%
    count(outlier) %>%
    pivot_wider(names_from=outlier,values_from=n) %>%
    rename(outlier_rare_pairs=outlier, inlier_rare_pairs=inlier)

# compute enrichment
enrichment_df  <- merge(count_table,rare_count_table,by="thresh",all=T) %>% mutate(numerator=outlier_rare_pairs/outlier_all_pairs, denominator=inlier_rare_pairs/inlier_all_pairs, enrichment=numerator/denominator)

# confidence intervals
enrichment_df <- enrichment_df %>% mutate(log_se = sqrt(1/outlier_rare_pairs - 1/outlier_all_pairs + 1/inlier_rare_pairs - 1/inlier_all_pairs), lower_CI = enrichment * exp(-1.96*log_se), upper_CI = enrichment * exp(1.96*log_se))


# sorting rows by z score threshold
enrichment_df$sortcol <- as.numeric(gsub("outlier_status_at_thresh_", "", enrichment_df$thresh))
enrichment_df <- arrange(enrichment_df, sortcol)

enrichment_plot <- ggplot(enrichment_df, aes(x = sortcol, y = enrichment)) +
  geom_point(size = 2) + 
  geom_text(aes(label = outlier_all_pairs), hjust = 0.7, vjust = -4) + 
  geom_errorbar(aes(ymax = upper_CI, ymin = lower_CI))
print(enrichment_plot + labs(title="Enrichment of rare variants in outlier genes \n(genes can have no outlier individuals)", x = "Z-score threshold"))

```